[[https://github.com/johannes-mueller/dired-gitignore.el/actions/workflows/test.yml][https://github.com/johannes-mueller/dired-gitignore.el/actions/workflows/test.yml/badge.svg]]

* dired-gitignore

dired minor mode to ignore files that are to be ignored by git.

** Purpose

Sometimes the working copy directories of your git repos get flooded with
temporary files, log files, cache stuff – in short files not belonging to the
repo and ignored by git.  At those times you might wish for a convenient way to
hide those files in your =dired= buffer.  If yes, =dired-gitignore= is
for you.

Hide and show the gitignored files by a simple configurable keystroke.


** Installation

As of now the easiest way of installing it is to use [[https://github.com/raxod502/straight.el][straight.el]]. Put the
following lines into your startup file.

#+BEGIN_EXAMPLE emacs-lisp
(straight-use-package
 '(dired-gitignore :type git :host github :repo "johannes-mueller/dired-gitignore.el"))
#+END_EXAMPLE


** Usage

Just bind the command =(dired-gitignore-mode)= to some key of your choice. For
example by putting something like

#+BEGIN_EXAMPLE emacs-lisp
(define-key dired-mode-map (kbd "h") #'dired-gitignore-mode)
#+END_EXAMPLE

into your startup files.  Then you will hide and show the gitignored files in a
dired buffer by hitting the =H= key.


** Status

This is basically the result of a rainy Sunday afternoon hack.  So probably not
everything will work under any circumstances.  Bug reports and feedback welcome
in the issue tracker.  Pull requests also, of course.

** Alternatives

There is a way more sophisticated package =dired-filter.el= of the
[[https://github.com/Fuco1/dired-hacks][=dired-hacks=]] suite.  It can do things like this one and many more.  So if you
have more complicated needs regarding filtering in =dired= this might be a
better bet for you.  However, =dired-filter.el= is also more complex, it has
more than 1200 lines of code plus some heavy dependencies as opposed to less
than 100 in =dired-gitignore= with =dired= as only dependency.

** Credits

This package has been inspired by [[https://github.com/mattiasb/dired-hide-dotfiles][dired-hide-dotfiles]].
